services:
  - type: web
    name: sun-festival-carpool
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm run prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
    healthCheckPath: /api/health 